name: CMake

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Configure
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Test
      run: ${{github.workspace}}/build/test_test

#   - name: Test
#     working-directory: ${{github.workspace}}/build
#     # Execute tests defined by the CMake configuration.
#     # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
#    run: ctest -C ${{env.BUILD_TYPE}}

    - name: Report
      uses: mikepenz/action-junit-report@v3
      if: always() # always run even if the previous step fails
      with:
        report_paths: 'report.xml'
        check_name: 'report'

    - name: Report2
        uses: dorny/test-reporter@v1
        if: always()    # run this step even if previous step failed
        with:
          name: report2    # Name of the check run which will be created
          path: report.xml    # Path to test results
          reporter: jest-junit        # Format of test results